# Generated by Django 4.2.7 on 2025-04-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='дата заезда')),
                ('check_out_date', models.DateField(verbose_name='дата выезда')),
                ('guests_count', models.PositiveSmallIntegerField(default=1, verbose_name='количество гостей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено'), ('canceled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=15, verbose_name='статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'бронирование',
                'verbose_name_plural': 'бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('days_before_checkin', models.PositiveIntegerField(help_text='За сколько дней до заезда можно отменить бронирование без штрафа', verbose_name='дней до заезда')),
                ('cancellation_fee_percentage', models.PositiveIntegerField(help_text='Процент от общей стоимости, который взимается при отмене бронирования позже указанного срока', verbose_name='процент штрафа')),
            ],
            options={
                'verbose_name': 'политика отмены',
                'verbose_name_plural': 'политики отмены',
            },
        ),
    ]
